### ISSUE TITLE
rerender not calling didInsertElement

### ISSUE THREAD

**Issue by ZackMattor** [emberjs/ember-legacy-views#14]
I know that Ember 1.13 still has the view code in it so i'm not sure if this should be here or in the the main codebase, but I added this addon to squelch the messages and assumed it would just pipe that view logic through the addon?

Anyways.. My problem is that before 1.13 `rerender` would re-call `didInsertElement` for views, and now it's not? If this is the desired behavior i'll just move up the priority for me to re-work this section of our app.

**Comment by rwjblue** [comment]
`rerender` in 1.12 and lower called `didInsertElement` because the old element was removed, and a new one was created.  In 1.13 and above, the element itself is stable and is only inserted once.  `didInsertElement` is only called when an element is actually inserted (and we are now preserving the element for performance reasons).  You can implement `didRender` to get something similar to what you are looking for.

We generally do not consider this to be a bug though.
